#!/usr/bin/env lua
-- Run this from the command line
local tests = require('tests')
local failures = tests.runtests()
-- tests.testPerformance()
if #failures > 0 then
  os.exit(1) -- signal failure
end
