#!/usr/bin/env lua
local orig_globs = {}
for k,v in pairs(_G) do orig_globs[k] = 1 end
-- Run this from the command line
local tests = require('tests')
local debug = false
local failures = tests.runtests(debug)
tests.testPerformance()
for k,v in pairs(_G) do if not orig_globs[k] then failures[#failures + 1] = true; print(("Leaked variable! %s"):format(k)) end end
if #failures > 0 then
  os.exit(1) -- signal failure
end
